---
- name: Download and dearmor Elasticsearch GPG key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add Elasticsearch repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: "elastic-8.x"
    update_cache: yes

- name: Install Elasticsearch
  ansible.builtin.apt:
    name: elasticsearch
    state: latest
    update_cache: yes


- name: Ensure Elasticsearch directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'
  loop:
    - /var/lib/elasticsearch
    - /var/log/elasticsearch

- name: Configure Elasticsearch
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0644'
  notify: restart elasticsearch

- name: Start and enable Elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: started
    enabled: yes
    daemon_reload: yes

- name: Verify Elasticsearch is running
  ansible.builtin.uri:
    url: "http://localhost:9200"
    method: GET
    status_code: 200
  register: es_health
  until: es_health.status == 200
  retries: 5
  delay: 10
