- name: Install Kibana
  apt:
    name: kibana
    state: latest

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

- name: Start and enable Kibana
  service:
    name: kibana
    state: started
    enabled: yes
