---
- hosts: zabbix
  become: true
  vars:
    zabbix_listen_port: 10051
    zabbix_db_host: "localhost"
    zabbix_db_name: "zabbix"
    zabbix_db_user: "zabbix"
    mysql_root_password: "zabbix"
    zabbix_db_password: "zabbix"
    zabbix_db_port: 3306
  roles:
    - ../roles/zabbix
